/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AiDisclaimerRouteImport } from './routes/ai-disclaimer'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTicketsRouteImport } from './routes/api/tickets'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets.$ticketId'
import { Route as ApiAdminSettingsRouteImport } from './routes/api/admin/settings'
import { Route as ApiAiClassifyRouteImport } from './routes/api/ai/classify'
import { Route as ApiAiReplyRouteImport } from './routes/api/ai/reply'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as ApiEmailSendRouteImport } from './routes/api/email/send'
import { Route as ApiStaffRouteImport } from './routes/api/staff'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TrackRouteImport } from './routes/track'
import { Route as ApiTicketTrackRouteImport } from './routes/api/ticket-track'
import { Route as SessionTokenRouteImport } from './routes/session.$token'
import { Route as ApiAdminEntityRouteImport } from './routes/api/admin/entity'
import { Route as ApiRemoteSessionsRouteImport } from './routes/api/remote-sessions'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AiDisclaimerRoute = AiDisclaimerRouteImport.update({
  id: '/ai-disclaimer',
  path: '/ai-disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketsRoute = ApiTicketsRouteImport.update({
  id: '/api/tickets',
  path: '/api/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/tickets/$ticketId',
  path: '/tickets/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiClassifyRoute = ApiAiClassifyRouteImport.update({
  id: '/api/ai/classify',
  path: '/api/ai/classify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiReplyRoute = ApiAiReplyRouteImport.update({
  id: '/api/ai/reply',
  path: '/api/ai/reply',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailSendRoute = ApiEmailSendRouteImport.update({
  id: '/api/email/send',
  path: '/api/email/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStaffRoute = ApiStaffRouteImport.update({
  id: '/api/staff',
  path: '/api/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketTrackRoute = ApiTicketTrackRouteImport.update({
  id: '/api/ticket-track',
  path: '/api/ticket-track',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionTokenRoute = SessionTokenRouteImport.update({
  id: '/session/$token',
  path: '/session/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEntityRoute = ApiAdminEntityRouteImport.update({
  id: '/api/admin/entity',
  path: '/api/admin/entity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemoteSessionsRoute = ApiRemoteSessionsRouteImport.update({
  id: '/api/remote-sessions',
  path: '/api/remote-sessions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/tickets': typeof TicketsRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/ai-disclaimer': typeof AiDisclaimerRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tickets': typeof ApiTicketsRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/ai/classify': typeof ApiAiClassifyRoute
  '/api/ai/reply': typeof ApiAiReplyRoute
  '/staff': typeof StaffRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/staff': typeof ApiStaffRoute
  '/reports': typeof ReportsRoute
  '/track': typeof TrackRoute
  '/api/ticket-track': typeof ApiTicketTrackRoute
  '/session/$token': typeof SessionTokenRoute
  '/api/admin/entity': typeof ApiAdminEntityRoute
  '/api/remote-sessions': typeof ApiRemoteSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/tickets': typeof TicketsRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/ai-disclaimer': typeof AiDisclaimerRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tickets': typeof ApiTicketsRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/ai/classify': typeof ApiAiClassifyRoute
  '/api/ai/reply': typeof ApiAiReplyRoute
  '/staff': typeof StaffRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/staff': typeof ApiStaffRoute
  '/reports': typeof ReportsRoute
  '/track': typeof TrackRoute
  '/api/ticket-track': typeof ApiTicketTrackRoute
  '/session/$token': typeof SessionTokenRoute
  '/api/admin/entity': typeof ApiAdminEntityRoute
  '/api/remote-sessions': typeof ApiRemoteSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/tickets': typeof TicketsRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/ai-disclaimer': typeof AiDisclaimerRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/tickets': typeof ApiTicketsRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/ai/classify': typeof ApiAiClassifyRoute
  '/api/ai/reply': typeof ApiAiReplyRoute
  '/staff': typeof StaffRoute
  '/api/email/send': typeof ApiEmailSendRoute
  '/api/staff': typeof ApiStaffRoute
  '/reports': typeof ReportsRoute
  '/track': typeof TrackRoute
  '/api/ticket-track': typeof ApiTicketTrackRoute
  '/session/$token': typeof SessionTokenRoute
  '/api/admin/entity': typeof ApiAdminEntityRoute
  '/api/remote-sessions': typeof ApiRemoteSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/tickets'
    | '/tickets/$ticketId'
    | '/ai-assistant'
    | '/ai-disclaimer'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/api/chat'
    | '/api/tickets'
    | '/api/admin/settings'
    | '/api/ai/classify'
    | '/api/ai/reply'
    | '/staff'
    | '/api/email/send'
    | '/api/staff'
    | '/reports'
    | '/track'
    | '/api/ticket-track'
    | '/session/$token'
    | '/api/admin/entity'
    | '/api/remote-sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/tickets'
    | '/tickets/$ticketId'
    | '/ai-assistant'
    | '/ai-disclaimer'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/api/chat'
    | '/api/tickets'
    | '/api/admin/settings'
    | '/api/ai/classify'
    | '/api/ai/reply'
    | '/staff'
    | '/api/email/send'
    | '/api/staff'
    | '/reports'
    | '/track'
    | '/api/ticket-track'
    | '/session/$token'
    | '/api/admin/entity'
    | '/api/remote-sessions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/tickets'
    | '/tickets/$ticketId'
    | '/ai-assistant'
    | '/ai-disclaimer'
    | '/contact'
    | '/cookies'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/api/chat'
    | '/api/tickets'
    | '/api/admin/settings'
    | '/api/ai/classify'
    | '/api/ai/reply'
    | '/staff'
    | '/api/email/send'
    | '/api/staff'
    | '/reports'
    | '/track'
    | '/api/ticket-track'
    | '/session/$token'
    | '/api/admin/entity'
    | '/api/remote-sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  TicketsRoute: typeof TicketsRoute
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AiDisclaimerRoute: typeof AiDisclaimerRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiTicketsRoute: typeof ApiTicketsRoute
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
  ApiAiClassifyRoute: typeof ApiAiClassifyRoute
  ApiAiReplyRoute: typeof ApiAiReplyRoute
  StaffRoute: typeof StaffRoute
  ApiEmailSendRoute: typeof ApiEmailSendRoute
  ApiStaffRoute: typeof ApiStaffRoute
  ReportsRoute: typeof ReportsRoute
  TrackRoute: typeof TrackRoute
  ApiTicketTrackRoute: typeof ApiTicketTrackRoute
  SessionTokenRoute: typeof SessionTokenRoute
  ApiAdminEntityRoute: typeof ApiAdminEntityRoute
  ApiRemoteSessionsRoute: typeof ApiRemoteSessionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-disclaimer': {
      id: '/ai-disclaimer'
      path: '/ai-disclaimer'
      fullPath: '/ai-disclaimer'
      preLoaderRoute: typeof AiDisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/tickets/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickets': {
      id: '/api/tickets'
      path: '/api/tickets'
      fullPath: '/api/tickets'
      preLoaderRoute: typeof ApiTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  TicketsRoute: TicketsRoute,
  TicketsTicketIdRoute: TicketsTicketIdRoute,
  AiAssistantRoute: AiAssistantRoute,
  AiDisclaimerRoute: AiDisclaimerRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiTicketsRoute: ApiTicketsRoute,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
  ApiAiClassifyRoute: ApiAiClassifyRoute,
  ApiAiReplyRoute: ApiAiReplyRoute,
  StaffRoute: StaffRoute,
  ApiEmailSendRoute: ApiEmailSendRoute,
  ApiStaffRoute: ApiStaffRoute,
  ReportsRoute: ReportsRoute,
  TrackRoute: TrackRoute,
  ApiTicketTrackRoute: ApiTicketTrackRoute,
  SessionTokenRoute: SessionTokenRoute,
  ApiAdminEntityRoute: ApiAdminEntityRoute,
  ApiRemoteSessionsRoute: ApiRemoteSessionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
